== Boost.System

Boost.System özünde hataları tanımlamak için dört sınıf tanımlayan bir kütüphanedir. Dört sınıfın hepsi C + + 11 ile standart kütüphaneye eklendi. Geliştirme ortamınız C + + 11'i destekliyorsa, Boost.System kullanmanıza gerek yoktur. Ancak, birçok Boost kitaplığı Boost.System kullandığından, bu diğer kitaplıklar aracılığıyla Boost.System ile karşılaşabilirsiniz.

Boost::system::error_code, Boost.System içindeki en temel sınıftır; işletim sistemine özgü hataları temsil eder. İşletim sistemleri genellikle hataları numaralandırdığından boost::system::error_code, int türünde bir değişkene hata kodu kaydeder. Aşağıdaki örnekte, bu sınıfın nasıl kullanılacağını gösterir.

Örneğin;

[source,c++]
----
#include <boost/system/error_code.hpp>
#include <iostream>

using namespace boost::system;

void fail(error_code &ec){ //hata döndürmek için fail() fonksiyonu tanımlanır
//fail() fonksiyonunun başarısız olup olmadığını algılaması için boost::system::error_code türünde bir nesne referans olarak iletilir.
  ec = errc::make_error_code(errc::not_supported);
}
//Boost.System boost::system::errc ad alanında çok sayıda hata kodu tanımlar.
// Örnekte, ec için boost::system::errc::not_supported hata kodunu atar.

int main()
{
  error_code ec;
  fail(ec);
  std::cout <<"Hata kodu: "<< ec.value() << '\n';//main() 'de, ec üzerinde value() çağrılır. Bu fonksiyon, nesnede depolanan hata kodunu döndürür.
  std::cout <<"Hata katogari adi: "<< ec.category().name() << '\n';
 //category() bir hatanın kategorisini döndürür. Bu, boost :: system :: error_category türünde bir nesnedir.
 //category().name() hata kategorisinin adını döndürür.

  boost::system::error_condition ecnd = ec.default_error_condition();
  std::cout << ecnd.value() << '\n';
  std::cout << ecnd.category().name() << '\n';

  //Platforma bağlı hata kodları için boost::system::error_code sınıfı kullanılırken, platformdan bağımsız hata kodlarına erişmek için
  // boost::system::error_condition kullanılır. default_error_condition(), platforma bağlı bir hata kodunu,
  // boost::system::error_condition türünde platformdan bağımsız bir hata koduna çevirir.
}
----


Ekran Çıktısı: 
 
 Hata kodu: 95
 Hata katogari adi: generic
 95
 generic



Örnekte, hata döndürmek için fail() fonksiyonu tanımlanır. fail() fonksiyonunun başarısız olup olmadığını algılaması için boost::system::error_code türünde bir nesne referans olarak iletilir. Boost kütüphaneleri tarafından sağlanan birçok işlev bu şekilde boost::system::error_code kullanır. Örneğin, Boost.Asio, boost::system::error_code türünde bir nesneyi geçirebileceğiniz boost::asio::ip::host_name() fonksiyonunu sağlar.

Boost.System boost::system::errc ad alanında çok sayıda hata kodu tanımlar. Örnekte, ec için boost::system::errc::not_supported hata kodunu atar. Boost::system::errc::not_supported bir sayı ve ec, boost::system::error_code türünde bir nesne olduğu için boost::system::errc::make_error_code() fonksiyonu çağrılır. Bu fonksiyon, ilgili hata koduyla boost::system::error_code türünde bir nesne oluşturur.

*main() 'de, ec üzerinde value() çağrılır. Bu fonksiyon, nesnede depolanan hata kodunu döndürür.*

*Varsayılan olarak 0, hata olmadığı anlamına gelir.* Diğer her sayı bir hatayı ifade eder. Hata kodu değerleri işletim sistemine bağlıdır. Hata kodlarının açıklaması için işletim sisteminizin belgelerine bakın.

value() fonksiyonuna ek olarak boost::system::error_code, boost::system::error_category türünde bir nesne döndüren category() fonksiyonunu  sağlar.

Hata kodları sadece sayısal değerlerdir. Microsoft gibi işletim sistemi üreticileri, sistem hata kodlarının benzersizliğini garanti ederken, hata kodlarını mevcut tüm uygulamalarda benzersiz tutmak uygulama geliştiricileri için neredeyse imkansızdır. Aynı kodları farklı hatalar için tekrar kullanmaktan kaçınmak için dünyadaki tüm yazılım geliştiricilerinin hata kodlarıyla dolu merkezi bir veritabanı gerektirir. Bu pratik olmadığı için hata kategorileri mevcuttur.

Boost::system::error_code türündeki hata kodları, category() fonksiyonu ile alınabilen bir kategoriye aittir. Boost::system::errc::make_error_code() ile oluşturulan hatalar otomatik olarak genel kategoriye girer. Bu, açıkça başka bir kategoriye atanmamışlarsa ait olan kategori hatalarıdır.

Platforma bağlı hata kodları için boost::system::error_code sınıfı kullanılırken, platformdan bağımsız hata kodlarına erişmek için
boost::system::error_condition kullanılır. default_error_condition(), platforma bağlı bir hata kodunu, boost::system::error_condition türünde platformdan bağımsız bir hata koduna çevirir.


Kodların doğru bir şekilde çalışması için CMakeLists.txt dosyası aşağıdaki gibi düzenlenmelidir.

[source,c++]
----
cmake_minimum_required(VERSION 3.5)
project(sample1)

set(CMAKE_CXX_STANDARD 17)

set(BOOST_ROOT "~/home/asli/Downloads/boost_1_71_0/")

link_directories(${Boost_LIBRARY_DIRS})


find_package(Boost 1.71.0
        REQUIRED date_time filesystem system iostreams system unit_test_framework
        ${BOOST_PYTHON})

include_directories(SYSTEM ${Boost_INCLUDE_DIRS})
link_directories(${Boost_LIBRARY_DIRS})

set(CMAKE_REQUIRED_INCLUDES ${CMAKE_INCLUDE_PATH} ${Boost_INCLUDE_DIRS})
set(CMAKE_REQUIRED_LIBRARIES ${Boost_LIBRARIES} icuuc ${PROFILE_LIBS})

if(NOT Boost_FOUND)
    message(FATAL_ERROR "Could not find boost!")
endif()

include_directories(${Boost_INCLUDE_DIRS})

add_executable(sample1 main.cpp)

target_link_libraries(sample1  ${Boost_LIBRARIES})
----
