== Boost.Chrono

Boost.Chrono kütüphanesi çeşitli saatler sunar. Örneğin, geçerli saati alabilir veya bir işlemde geçirilen zamanı ölçebilirsiniz.

Boost.Chrono'nun bölümleri Cplusplus 11'e eklendi. Geliştirme ortamınız C+plusplus 'i destekliyorsa, başlık dosyası chrono'da tanımlanan birkaç saate erişiminiz vardır. Ancak, C plusplus 11, CPU saatini ölçmek için saatler gibi bazı özellikleri desteklemez. Ayrıca, yalnızca Boost.Chrono kullanıcı tanımlı çıktı biçimlerini zamanla destekler.

Boost.Chrono saatlerinin tümüne boost/chrono.hpp başlık dosyası aracılığıyla erişebilirsiniz. Tek uzantı, boost/chrono_io.hpp başlık dosyası gerektiren kullanıcı tanımlı biçimlendirmedir.

Örneğin;

[source,c++]
----
#include <boost/chrono.hpp>
#include <iostream>

using namespace boost::chrono;
using  namespace std;

int main()
{
  cout << system_clock::now() << endl; //boost::chrono::system_clock sistem saatini döndürür. Bu genellikle bilgisayarınızın
  // masaüstünde görüntülenen zamandır. Bilgisayarınızdaki saati değiştirirseniz boost::chrono::system_clock yeni saati döndürür.
#ifdef BOOST_CHRONO_HAS_CLOCK_STEADY
  cout << steady_clock::now() << endl;//son önyüklemeden bu yana geçen süreyi ölçer.
#endif
  cout << high_resolution_clock::now() << endl;//hangi saatin zamanı daha hassas ölçtüğünü ölçer.

#ifdef BOOST_CHRONO_HAS_PROCESS_CLOCKS
  cout << process_real_cpu_clock::now() << endl;//bir işlemin çalıştığı CPU zamanını döndürür.
  cout << process_user_cpu_clock::now() << endl;//yalnızca kullanıcı alanında çalışmak için harcanan zamanı döndürür
  cout << process_system_cpu_clock::now() << endl;//boost::chrono::process_user_cpu_clock ile benzerdir. Ancak bu saat çekirdek alanında harcanan zamanı ölçer.
  cout << process_cpu_clock::now() << endl;//boost::chrono::process_real_cpu_clock, boost::chrono::process_user_cpu_clock ve
  // boost::chrono::process_system_cpu_clock tarafından döndürülen CPU zamanlarını içeren bir grup döndürür
#endif

#ifdef BOOST_CHRONO_HAS_THREAD_CLOCK
  cout << thread_clock::now() << endl;//Bir iş parçacığı(process) tarafından kullanılan zamanı döndürür.
#endif
}
----

Ekran Çıktısı:
 
 1580419475195158233 nanoseconds since Jan 1, 1970
 4591916472770 nanoseconds since boot
 4591916475077 nanoseconds since boot
 17184161100000000 nanoseconds since process start-up
 140000000 nanoseconds since process start-up
 120000000 nanoseconds since process start-up
 {17184161100000000;140000000;120000000} nanoseconds since process start-up
 274494393 nanoseconds since thread start-up


Örnek Boost.Chrono tarafından sağlanan tüm saatleri sunar. Tüm saatler ortak  fonksiyonuna now() sahiptir, bu bir zaman noktası döndürür. Tüm zaman noktaları evrensel olarak geçerli bir zaman noktasına göredir. Bu referans zaman noktasına *epoch* denir. Sık kullanılan bir dönem 1 Ocak 1970'tir. Örnekte, görüntülenen her zaman noktası için dönemi yazmaktadır.

*boost::chrono::system_clock:* Sistem saatini döndürür. Bu genellikle bilgisayarınızın masaüstünde görüntülenen zamandır. Bilgisayarınızdaki saati değiştirirseniz boost::chrono::system_clock yeni saati döndürür. Örnekte, standart çıktıya şöyle yazar: 1 Ocak 1970'ten bu yana 13919594042183544 saniye [1/10000000] saniye.


*boost::chrono::steady_clock* Daha sonra erişildiğinde her zaman daha sonra geri dönecek bir saattir. Zaman bir bilgisayara geri ayarlanmış olsa bile, boost::chrono::steady_clock daha sonra geri dönecektir. Bu kez monotonik zaman olarak bilinir.

Örnekte, sistem önyüklendiğinden beri nanosaniye sayısını görüntüler. Mesaj aşağıdaki gibi görünüyor: 10594369282958 önyüklemeden bu yana nanosaniye. boost::chrono::steady_clock, son önyüklemeden bu yana geçen süreyi ölçer. Ancak, son önyüklemeden bu yana ölçümü başlatmak bir uygulama ayrıntısıdır. Referans noktası farklı bir uygulama ile değişebilir.

[IMPORTANT]
====
Boost::chrono::steady_clock tüm platformlarda desteklenmez. Saat yalnızca BOOST_CHRONO_HAS_CLOCK_STEADY tanımlanmışsa kullanılabilir.
====

*boost::chrono::high_resolution_clock:* Hangi saatin zamanı daha hassas ölçtüğüne bağlı olarak boost::chrono::system_clock veya boost::chrono::steady_clock için bir tür tanımıdır. 

*boost::chrono::process_real_cpu_clock:* Bir işlemin çalıştığı CPU zamanını döndürür. Saat, programın başlamasından bu yana geçen zamanı ölçer. Örnekte, standart çıktıya şöyle yazar: işlem başlangıcından bu yana 1000000 nanosaniye.

[IMPORTANT]
====
Boost::chrono::process_real_cpu_clock saat ve CPU saatini ölçen diğer saatler sadece BOOST_CHRONO_HAS_PROCESS_CLOCKS tanımlanmışsa kullanılabilir.
====


*boost::chrono::process_user_cpu_clock:*  Yalnızca kullanıcı alanında çalışmak için harcanan zamanı döndürür. Bir program, örneğin Windows Sleep() fonksiyonu aracılığıyla bir süre durdurulursa, Sleep() öğesinde harcanan süre boost::chrono::process_user_cpu_clock ile ölçülmez.

Örnekte, standart çıktıya şöyle yazar: işlemin başlamasından bu yana 15600100 nanosaniye.


*boost::chrono::process_system_cpu_clock:* boost::chrono::process_user_cpu_clock ile benzerdir. Ancak bu saat çekirdek alanında harcanan zamanı ölçer. Boost::chrono::process_system_cpu_clock, bir işlemin işletim sistemi işlevlerini yürütmek için harcadığı CPU süresini döndürür.

Örnekte, standart çıktıya şöyle yazar: işlem başlangıcından bu yana 0 nanosaniye. Bu örnek işletim sistemi işlevlerini doğrudan aramadığından ve Boost.Chrono yalnızca birkaç işletim sistemi işlevi kullandığından, boost::chrono::process_system_cpu_clock 0 döndürebilir.

*boost::chrono::process_cpu_clock:* boost::chrono::process_real_cpu_clock, boost::chrono::process_user_cpu_clock ve boost::chrono::process_system_cpu_clock tarafından döndürülen CPU zamanlarını içeren bir grup döndürür. Örnekte, standart çıktıya şöyle yazar: {1000000; 15600100; 0} işlemin başlamasından bu yana nanosaniye.


*boost::chrono::thread_clock:* Bir iş parçacığı tarafından kullanılan zamanı döndürür.Boost::chrono::thread_clock ile ölçülen süre, işlem başına değil, iş parçacığı başına haricinde CPU süresiyle karşılaştırılabilir. boost::chrono::thread_clock, iş parçacığının çalıştığı CPU zamanını döndürür. Kullanıcı ve çekirdek alanında harcanan zaman arasında ayrım yapmaz.

boost::chrono::thread_clock tüm platformlarda desteklenmez. Makro boost_chrono_has_thread_clock tanımlanmışsa, yalnızca boost::chrono::thread_clock kullanabilirsiniz.

Örnekte,standart çıktıya şöyle yazar: iş parçacığı başlatılmasından bu yana 15600100 nanosaniye.


Kodların doğru bir şekilde çalışması için CMakeLists.txt dosyası aşağıdaki gibi düzenlenmelidir.

[source,c++]
----
cmake_minimum_required(VERSION 3.5)
project(sample1)

set(CMAKE_CXX_STANDARD 17)

set(BOOST_ROOT "~/home/asli/Downloads/boost_1_71_0/")

#find_package(Boost 1.7 COMPONENTS system filesystem chrono REQUIRED)

link_directories(${Boost_LIBRARY_DIRS})


find_package(Boost 1.71.0
        REQUIRED date_time filesystem system iostreams chrono unit_test_framework
        ${BOOST_PYTHON})

include_directories(SYSTEM ${Boost_INCLUDE_DIRS})
link_directories(${Boost_LIBRARY_DIRS})

set(CMAKE_REQUIRED_INCLUDES ${CMAKE_INCLUDE_PATH} ${Boost_INCLUDE_DIRS})
set(CMAKE_REQUIRED_LIBRARIES ${Boost_LIBRARIES} icuuc ${PROFILE_LIBS})

if(NOT Boost_FOUND)
    message(FATAL_ERROR "Could not find boost!")
endif()

include_directories(${Boost_INCLUDE_DIRS})

add_executable(sample1 main.cpp)

target_link_libraries(sample1  ${Boost_LIBRARIES})
----











